request rest :

@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJmNGMwYzdiLWEzOGItNDkyMi1hZWJlLWQ1MzVkNjhhOWZkOCIsInVzZXJOYW1lIjoiVGVzdFBhcnRpY2lwYW50VXNlciIsImNyZWF0ZWRBdCI6IjIwMjUtMTAtMzBUMTQ6MjI6MjEuMDAwWiIsImlhdCI6MTc2MTgzNDQ0MiwiZXhwIjoxNzYxOTIwODQyfQ.UUVrsp1rM6zR9ub8kWyj0u_XqSXHkf-T4jmzw04Tweg



###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json

###
GET http://localhost:5000/api/v1/seeder/trainingSeeder
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/seeder/participantSeeder
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "TestParticipantUser",
      "password" : "TestParticipantUser1!"
}

###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin1!0)"
}


###
POST  http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{     "userName"    : "participant",
      "password" : "Participant!0)"
}




###
GET  http://localhost:5000/api/v1/auth/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:5000/api/v1/setting/edit-participant-profile/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "participant1@example.com",
  "firstName": "Budi",
  "lastName": "Santoso",
  "company": "PT Teknologi Nusantara",
  "companyAddress": "Jl. Merdeka No. 123, Jakarta",
  "phone": "081234567890",
  "jobTitle": "Software Engineer",
  "officePhone": "021555666",
  "message": "Saya ingin ikut training tambahan",
  "status": "sedangBerlangsung"
}



###
PUT http://localhost:5000/api/v1/setting/edit-admin-profile/:id
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userName": "Admin Utama",
  "email": "admin@example.com",
  "phone": "081298765432",
  "password": "AdminBaru!2025",
  "image": "https://example.com/uploads/admin-profile.png"
}


###
GET http://localhost:5000/api/v1/dashboard/dashboard-data
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  http://localhost:5000/api/v1/user-management/get-all-user
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/user-management/get-user-by-id/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/user-management/create-user
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "username"  : "TESTAdjustEndpoint",
    "password"  : "TESTAdjustEndpoint123!",
    "role"      : "PARTICIPANT"

}

###
PUT  http://localhost:5000/api/v1/user-management/update-user/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}


{     
    "username"    : "TESTParticipant2",
    "password"    : "Admin1!Update",
    "role"    : "PARTICIPANT",

}


###
DELETE  http://localhost:5000/api/v1/user-management/delete-user/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}






###
GET http://localhost:5000/api/v1/coach/get-all-coach?page=1&limit=5
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/coach/get-coach-by-id/5b74083b-6214-4f9d-8e3a-c8b9c26836d4
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/coach/create-coach
Content-Type: application/json
Authorization: Bearer {{token}}

{     "coachName"    : "Test Adjust Enpoint"
}

###
PUT  http://localhost:5000/api/v1/coach/update-coach/0aab4dae-5393-4e8e-aa59-f74cd58fcf07
Content-Type: application/json
Authorization: Bearer {{token}}

{     "coachName"    : "Update Jafal"
}


###
DELETE  http://localhost:5000/api/v1/coach/delete-coach/0aab4dae-5393-4e8e-aa59-f74cd58fcf07
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET  http://localhost:5000/api/v1/category/get-all-category
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/category/get-category-by-id/217831a5-2e49-4ad5-b70f-cead576cce50
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/category/create-category
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "categoryName"    : "Test Adjust Endpoint",
    "trainingCode"    : "Adjust Endpoint-001"
}

###
PUT  http://localhost:5000/api/v1/category/update-category/ecf38f36-b0da-487a-b01c-d3ad6d874f8a
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "categoryName"    : "TestNewUpdateEndpoint",
    "trainingCode"    : "NewUpdate-003"
}


###
DELETE  http://localhost:5000/api/v1/category/delete-category/ecf38f36-b0da-487a-b01c-d3ad6d874f8a
Content-Type: application/json
Authorization: Bearer {{token}}






//Training endpoint
###
GET http://localhost:5000/api/v1/training/get-all-training?trainingName=&category=&start_date=&end_date=&limit=10&page=1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/training/get-training-by-id/afec26ea-8013-4cfe-beab-1751668a6c01
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST http://localhost:5000/api/v1/training/create-training
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "trainingName": "Digital Marketing Mastery",
  "categoryId": "fe44508a-30fc-4128-bfad-ce4e2dc3569c",
  "coachId": "3c31593d-e696-480b-bfcb-28878ab09ffb",
  "price": 2500000,
  "startDateTraining": "2025-11-10",
  "endDateTraining": "2025-11-15",
  "ttdImage": "https://cdn.example.com/signatures/signature_michael.png",
  "signatoryPosition": "Head of Training Department",
  "signatoryName": "Adjust Endpoint"
}



###
PUT  http://localhost:5000/api/v1/training/update-training/89cfea6f-376c-4a77-881a-416b999a6cc7
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "trainingName": "Pelatihan Manajemen Proyek Lanjutan",
  "price": 4500000,
  "categoryId": "fe44508a-30fc-4128-bfad-ce4e2dc3569c",
  "coachId": "3c31593d-e696-480b-bfcb-28878ab09ffb",
  "startDateTraining": "2025-12-10",
  "endDateTraining": "2025-12-20",
  "signatoryName": "Dr. Maya Rahman",
  "signatoryPosition": "Head of Training Department",
  "ttdImage": "https://cdn.example.com/signatures/maya.png"
}




###
DELETE  http://localhost:5000/api/v1/training/delete-training/89cfea6f-376c-4a77-881a-416b999a6cc7
Content-Type: application/json
Authorization: Bearer {{token}}





//Participant endpoint
###
GET  http://localhost:5000/api/v1/participant/get-all-participant
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/participant/get-participant-by-id/89cfea6f-376c-4a77-881a-416b999a6cc7
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1/participant/get-participant-by-training-id/afec26ea-8013-4cfe-beab-1751668a6c01
Authorization: Bearer {{token}}


// existing is false
###
POST  http://localhost:5000/api/v1/participant/create-participant
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "training": "afec26ea-8013-4cfe-beab-1751668a6c01",
  "participants": [
    {
      "isExisting": false,
      "email": "peserta.baru@example.com",
      "firstName": "Andi",
      "lastName": "Wijaya",
      "company": "PT Sejahtera Abadi",
      "companyAddress": "Jl. Merdeka No. 20",
      "phone": "081298765432",
      "jobTitle": "Staff Marketing",
      "officePhone": "0215550123",
      "message": "Pendaftaran untuk pelatihan Digital Marketing.",
      "user": "e3f61fee-fc90-4bab-b6e4-d9c4d3b3d917",
      "signatoryName": "Dr. Rina Hartati, M.T.",
      "signatoryPosition": "Kepala Bidang Pelatihan",
      "ttdImage": "https://example.com/signatures/rina.png"
    }
  ]
}



// existing is true
###
POST  http://localhost:5000/api/v1/participant/create-participant
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "training": "536eb561-9da9-4239-b236-8c727937cd0d",
  "participants": [
    {
      "isExisting": true,
      "participantId": "ef4dd204-4239-4c6c-96aa-0d3fdb584757"
    },
    {
      "isExisting": true,
      "participantId": "232ca3fd-a137-44ee-9efe-651314daf393"
    }
  ]
}



###
PUT  http://localhost:5000/api/v1/participant/update-participant/b2bc6117-c7d6-49e3-94d2-fff0dd026ca5
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "jane.smith@example.com",
    "firstName": "Jane",
    "lastName": "Smith",
    "company": "Innovate Inc",
    "companyAddress": "456 Innovate Ave",
    "phone": 1122334455,
    "jobTitle": "Data Analyst",
    "officePhone": 5544332211,
    "message": "Looking for advanced JavaScript training",
    "training": "920a59df-31c0-4d7a-9ad8-40d5e374243e",
    "user" : "99738b9d-e430-4d60-a44e-daf0433da4fe"
}



###
DELETE   http://localhost:5000/api/v1/participant/delete-participant/f20f5781-5def-4841-95a9-8abcd6c3c690
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:5000/api/v1/participant/change-status-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status" : "sedangBerlangsung"
}

###
PUT http://localhost:5000/api/v1/participant/restore-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/certificate/get-certificate-by-training-id/afec26ea-8013-4cfe-beab-1751668a6c01
Authorization: Bearer {{token}}

###
POST http://localhost:5000/api/v1/certificate/publish-certificate-by-training-id/7b794b58-6b9e-4f58-8c6f-49441ef72fe0
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "certificates": [
    {
      "trainingParticipantId": "d452c1b3-0184-4bcf-a446-fecc3d5c949e",
      "imageUrl": "https://example.com/certificates/cert-001.jpg",
      "noLiscense": "TESTCERT-001",
      "expiredAt": "2026-10-22"
    }
  ]
}


###
GET http://localhost:5000/api/v1/participant-dashboard/get-certificate
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/participant-dashboard/get-certificate-by-id/d4bba89b-9f48-493f-83fe-2aa422c36d17
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/participant-dashboard/get-summary-dashboard=participant
Content-Type: application/json
Authorization: Bearer {{token}}








