@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU2ZDA2ZWVmLTk4Y2UtNGViZi04NGNmLWFlNzEwMWE5YzRhYiIsInVzZXJOYW1lIjoiQWRtaW4xIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJjcmVhdGVkQXQiOiIyMDI1LTA5LTA0VDE2OjI5OjI1LjUzMFoiLCJpYXQiOjE3NTcwMDg5ODksImV4cCI6MTc1NzAwOTcwOX0.OrkSIl745ovhtwYPCRuafmCqPqWNGejWP_gMZuGzPqs







###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json



###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin1!0)"
}


###
GET  http://localhost:5000/api/v1/auth/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1/dashboard/dashboard-data
Content-Type: application/json
Authorization: Bearer {{token}}


//Training endpoint
###
GET http://localhost:5000/api/v1/training/get-all-training?trainingName=&category=&start_date=&end_date=&limit=10&page=1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/training/get-training-by-id/c3a81e76-051e-4b56-81e1-9fd508df6533
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST http://localhost:5000/api/v1/training/create-training
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trainingName": "Advanced JavaScript",
    "category": "Programming",
    "trainingCode": "JS201",
    "coach": "Jane Smith",
    "price": 200,
    "startDateTraining": "2023-11-01",
    "endDateTraining": "2023-11-10"
}


###
PUT  http://localhost:5000/api/v1/training/update-training/c3a81e76-051e-4b56-81e1-9fd508df6533
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trainingName": "update Advanced JavaScript",
    "category": "update Programming",
    "trainingCode": "update JS201",
    "coach": "update Jane Smith",
    "price": 300,
    "startDateTraining": "2025-11-01",
    "endDateTraining": "2025-11-10"
}




###
DELETE   http://localhost:5000/api/v1/training/delete-training/c3a81e76-051e-4b56-81e1-9fd508df6533
Content-Type: application/json
Authorization: Bearer {{token}}





//Participant endpoint
###
GET  http://localhost:5000/api/v1/participant/get-all-participant?firstName=John?=oemahWebsite
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/participant/get-participant-by-id/:id
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST  http://localhost:5000/api/v1/participant/create-participant
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "jane.smith@example.com",
    "firstName": "Jane",
    "lastName": "Smith",
    "company": "Innovate Inc",
    "companyAddress": "456 Innovate Ave",
    "phone": 1122334455,
    "jobTitle": "Data Analyst",
    "officePhone": 5544332211,
    "message": "Looking for advanced JavaScript training",
    "training": "f26db3b0-fe46-4e49-a457-079b4d63ba16"
}


###
PUT  http://localhost:5000/api/v1/participant/update-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "updatejane.smith@example.com",
    "firstName": "update Jane",
    "lastName": "update Smith",
    "company": "update Innovate Inc",
    "companyAddress": "update 456 Innovate Ave",
    "phone": 1111111,
    "jobTitle": "update Data Analyst",
    "officePhone": 1111,
    "message": "uupdate Looking for advanced JavaScript training"
}



###
DELETE   http://localhost:5000/api/v1/participant/delete-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:5000/api/v1/participant/change-status-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status" : "sedangBerlangsung"
}







