@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ1MjVlMWQ0LTgyYzgtNDNiNy1hNDQ4LWE4NDIyMTQ2OWRjZCIsInVzZXJOYW1lIjoiQWRtaW4xIiwiZW1haWwiOiIiLCJjcmVhdGVkQXQiOiIyMDI1LTA5LTI3VDEzOjAwOjMwLjE3MloiLCJpYXQiOjE3NTg5NzgwNTIsImV4cCI6MTc1OTA2NDQ1Mn0.TKOSi5isRaEhzz6HmNepXO-xK85Fmtt5IM21N2OYt_M



###
GET http://localhost:5000/api/v1/seeder/userSeeder
Content-Type: application/json

###
GET http://localhost:5000/api/v1/seeder/trainingSeeder
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/seeder/trainingSeeder
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:5000/api/v1/seeder/participantSeeder
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{     "userName"    : "Admin1",
      "password" : "Admin1!0)"
}


###
GET  http://localhost:5000/api/v1/auth/fetch
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:5000/api/v1/setting/edit-participant-profile/:id
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "participant1@example.com",
  "firstName": "Budi",
  "lastName": "Santoso",
  "company": "PT Teknologi Nusantara",
  "companyAddress": "Jl. Merdeka No. 123, Jakarta",
  "phone": "081234567890",
  "jobTitle": "Software Engineer",
  "officePhone": "021555666",
  "message": "Saya ingin ikut training tambahan",
  "status": "sedangBerlangsung"
}



###
PUT http://localhost:5000/api/v1/setting/edit-admin-profile/:id
Content-Type: application/json
Authorization: Bearer {{token}}
{
  "userName": "Admin Utama",
  "email": "admin@example.com",
  "phone": "081298765432",
  "password": "AdminBaru!2025",
  "image": "https://example.com/uploads/admin-profile.png"
}


###
GET http://localhost:5000/api/v1/dashboard/dashboard-data
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  http://localhost:5000/api/v1/user-management/get-all-user
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/user-management/get-user-by-id/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/user-management/create-user
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "username"  : "TestParticipant",
    "password"  : "Participant123!",
    "role"      : "PARTICIPANT",
    "phone"     : "00000000",
    "email"     : "Participant@gmail.com"

}

###
PUT  http://localhost:5000/api/v1/user-management/update-user/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}


{     
    "username"    : "TESTAdmin1Update",
    "password"    : "Admin1!Update",
    "role"    : "ADMIN",
    "phone"    : "11111111",
    "email"    : "TESTAdmin1Update@gmail.com"

}


###
DELETE  http://localhost:5000/api/v1/user-management/delete-user/4dfb572b-11c4-440e-a74f-adf482455fa5
Content-Type: application/json
Authorization: Bearer {{token}}









###
GET  http://localhost:5000/api/v1/training-coach/get-all-training-coach
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/training-coach/get-training-coach-by-id/d9564180-3b30-4651-aa73-99efe342e12d
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/training-coach/create-training-coach
Content-Type: application/json
Authorization: Bearer {{token}}

{     "coachName"    : "Jafal"
}

###
PUT  http://localhost:5000/api/v1/training-coach/update-training-coach/d9564180-3b30-4651-aa73-99efe342e12d
Content-Type: application/json
Authorization: Bearer {{token}}

{     "coachName"    : "Update Jafal"
}


###
DELETE  http://localhost:5000/api/v1/training-coach/delete-training-coach/d9564180-3b30-4651-aa73-99efe342e12d
Content-Type: application/json
Authorization: Bearer {{token}}



###
GET  http://localhost:5000/api/v1/training-category/get-all-training-category
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/training-category/get-training-category-by-id/7337b57e-6e12-4386-844d-7975dd70c03a
Content-Type: application/json
Authorization: Bearer {{token}}




###
POST  http://localhost:5000/api/v1/training-category/create-training-category
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "categoryName"    : "MANTA2",
    "trainingCode"    : "MANTA-002"

}

###
PUT  http://localhost:5000/api/v1/training-category/update-training-category/7337b57e-6e12-4386-844d-7975dd70c03a
Content-Type: application/json
Authorization: Bearer {{token}}

{     
    "categoryName"    : "Update Manta",
    "trainingCode"    : "MANTA-003"
}


###
DELETE  http://localhost:5000/api/v1/training-category/delete-training-category/7337b57e-6e12-4386-844d-7975dd70c03a
Content-Type: application/json
Authorization: Bearer {{token}}






//Training endpoint
###
GET http://localhost:5000/api/v1/training/get-all-training?trainingName=&category=&start_date=&end_date=&limit=10&page=1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/training/get-training-by-id/bf6dd6cf-c2e8-428b-91e9-660da199c395
Content-Type: application/json
Authorization: Bearer {{token}}



###
POST http://localhost:5000/api/v1/training/create-training
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trainingName": "Advanced Type Script 2",
    "category": "827b19d6-51ba-49af-9864-099b63fa6ccd",
    "trainingCode": "TS201",
    "coach": "08e7edf5-28f5-433b-a21f-52fb8a7803b5",
    "price": 20000,
    "startDateTraining": "2023-11-01",
    "endDateTraining": "2023-11-10"
}


###
PUT  http://localhost:5000/api/v1/training/update-training/bf6dd6cf-c2e8-428b-91e9-660da199c395
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "trainingName": "update Advanced JavaScript",
    "category": "827b19d6-51ba-49af-9864-099b63fa6ccd",
    "trainingCode": "update JS201",
    "coach": "08e7edf5-28f5-433b-a21f-52fb8a7803b5",
    "price": 300,
    "startDateTraining": "2025-11-01",
    "endDateTraining": "2025-11-10"
}




###
DELETE   http://localhost:5000/api/v1/training/delete-training/c6d43ea7-7c90-4b8c-b8ea-de82c3a5970d
Content-Type: application/json
Authorization: Bearer {{token}}





//Participant endpoint
###
GET  http://localhost:5000/api/v1/participant/get-all-participant
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET  http://localhost:5000/api/v1/participant/get-participant-by-id/2a8e839c-fd87-464a-a23a-13f3c46ea26d
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET http://localhost:5000/api/v1/participant/get-participant-by-training-id/8ec89ef3-027b-4b34-b166-5f2b35e8cad3?page=&limit=&search=
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST  http://localhost:5000/api/v1/participant/create-participant
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "jane.smith@example.com",
    "firstName": "Jane",
    "lastName": "Smith",
    "company": "Innovate Inc",
    "companyAddress": "456 Innovate Ave",
    "phone": 1122334455,
    "jobTitle": "Data Analyst",
    "officePhone": 5544332211,
    "message": "Looking for advanced JavaScript training",
    "training": "8ec89ef3-027b-4b34-b166-5f2b35e8cad3"
}


###
PUT  http://localhost:5000/api/v1/participant/update-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "updatejane.smith@example.com",
    "firstName": "update Jane",
    "lastName": "update Smith",
    "company": "update Innovate Inc",
    "companyAddress": "update 456 Innovate Ave",
    "phone": 1111111,
    "jobTitle": "update Data Analyst",
    "officePhone": 1111,
    "message": "uupdate Looking for advanced JavaScript training"
}



###
DELETE   http://localhost:5000/api/v1/participant/delete-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

###
PUT http://localhost:5000/api/v1/participant/change-status-participant/148bccde-6c45-428d-bd7c-40f5676836f0
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status" : "sedangBerlangsung"
}







